# Generated by Django 5.2.3 on 2025-10-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeparserconfig',
            name='default_backend',
            field=models.CharField(choices=[('auto', 'Auto (Gemini -> spaCy -> Rule-based)'), ('gemini', 'Gemini AI'), ('spacy', 'spaCy NLP'), ('rule_based', 'Rule-based')], default='auto', help_text='Default AI backend to use for processing', max_length=20),
        ),
        migrations.AddField(
            model_name='resumeparserconfig',
            name='enable_confidence_scoring',
            field=models.BooleanField(default=True, help_text='Enable confidence scoring for extracted data'),
        ),
        migrations.AddField(
            model_name='resumeparserconfig',
            name='enable_fallback_processing',
            field=models.BooleanField(default=True, help_text='Enable fallback to other backends if primary fails'),
        ),
        migrations.AddField(
            model_name='resumeparserconfig',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Google Gemini API key for AI processing', max_length=255),
        ),
        migrations.AddField(
            model_name='resumeparserconfig',
            name='max_file_size_mb',
            field=models.IntegerField(default=10, help_text='Maximum file size allowed for upload (in MB)'),
        ),
        migrations.AddField(
            model_name='resumeparserconfig',
            name='processing_timeout_seconds',
            field=models.IntegerField(default=300, help_text='Timeout for resume processing in seconds'),
        ),
        migrations.AddField(
            model_name='resumeparserconfig',
            name='spacy_model',
            field=models.CharField(default='en_core_web_sm', help_text='spaCy model to use for NLP processing', max_length=50),
        ),
        migrations.AddField(
            model_name='resumeparserconfig',
            name='temp_file_cleanup_timeout',
            field=models.IntegerField(default=300, help_text='Timeout for temporary file cleanup in seconds'),
        ),
    ]
