# Generated by Django 5.2.3 on 2025-10-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_resumeparserconfig_default_backend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeparserconfig',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Google Gemini API key for AI processing', max_length=255, null=True),
        ),
    ]
