# Generated by Django 5.2.3 on 2025-07-20 13:35

from django.db import migrations
from django.conf import settings
from django.utils import timezone


def create_initial_config(apps, schema_editor):
    """
    Create the initial SiteFilesConfig with default values.
    """
    SiteFilesConfig = apps.get_model('site_files', 'SiteFilesConfig')
    
    # Check if any configuration already exists
    if not SiteFilesConfig.objects.exists():
        # Determine the site URL from settings if available
        site_url = getattr(settings, 'SITE_URL', 'https://example.com')
        site_name = getattr(settings, 'SITE_NAME', 'My Site')
        
        # Create the initial configuration
        SiteFilesConfig.objects.create(
            site_name=site_name,
            site_url=site_url,
            sitemap_path='static/Sitemap.xml',
            robots_path='static/robots.txt',
            security_path='static/security.txt',
            llms_path='static/humans.txt',
            update_frequency='daily',
            update_sitemap=True,
            update_robots=True,
            update_security=True,
            update_llms=True,
            last_update=None,  # No updates have happened yet
        )


def remove_initial_config(apps, schema_editor):
    """
    Remove the initial configuration (for rollback).
    """
    SiteFilesConfig = apps.get_model('site_files', 'SiteFilesConfig')
    SiteFilesConfig.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('site_files', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_config, remove_initial_config),
    ]
