# Generated by Django 5.2.3 on 2025-08-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_files', '0002_add_initial_site_files_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefilesconfig',
            name='llms_path',
            field=models.CharField(default='humans.txt', help_text='Path to the LLMs.txt file relative to the project root', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitefilesconfig',
            name='robots_path',
            field=models.CharField(default='robots.txt', help_text='Path to the robots.txt file relative to the project root', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitefilesconfig',
            name='security_path',
            field=models.CharField(default='security.txt', help_text='Path to the security.txt file relative to the project root', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitefilesconfig',
            name='site_url',
            field=models.URLField(default='https://kabhishek18.com', help_text='Base URL of the website (e.g., https://kabhishek18.com)'),
        ),
        migrations.AlterField(
            model_name='sitefilesconfig',
            name='sitemap_path',
            field=models.CharField(default='sitemap.xml', help_text='Path to the sitemap file relative to the project root', max_length=255),
        ),
    ]
