# Generated by Django 5.2.3 on 2026-03-28 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A friendly name for this component (e.g., 'Homepage Hero Section').", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='The URL-friendly version of the title. Leave blank to auto-generate.', max_length=200, unique=True)),
                ('content', models.TextField(blank=True, help_text='The HTML content of the component.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kumar Abhishek', max_length=120)),
                ('active_theme', models.CharField(choices=[('others_3d', 'Others-3d'), ('portfolio_3d', 'portfolio-3d'), ('portfolio', 'portfolio')], default='others_3d', max_length=30)),
                ('enable_template_switch', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Theme Settings',
                'verbose_name_plural': 'Site Theme Settings',
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('database', 'Database'), ('cache', 'Cache'), ('memory', 'Memory'), ('disk', 'Disk'), ('system_load', 'System Load'), ('logs', 'Logs'), ('api', 'API'), ('celery', 'Celery'), ('redis', 'Redis'), ('overall', 'Overall System')], help_text='Type of health metric', max_length=50)),
                ('metric_value', models.JSONField(help_text='Detailed metric data in JSON format')),
                ('status', models.CharField(choices=[('healthy', '🟢 Healthy'), ('warning', '🟡 Warning'), ('critical', '🔴 Critical')], help_text='Health status of this metric', max_length=20)),
                ('message', models.TextField(help_text='Human-readable status message')),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this metric was recorded')),
            ],
            options={
                'verbose_name': 'Health Metric',
                'verbose_name_plural': 'Health Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name', '-timestamp'], name='core_health_metric__a5f6dd_idx'), models.Index(fields=['status', '-timestamp'], name='core_health_status_2dffbe_idx'), models.Index(fields=['-timestamp'], name='core_health_timesta_bb0f9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for this template set (e.g., 'Homepage Layout').", max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files', models.ManyToManyField(blank=True, help_text='Select the files that make up this template set. They will be included in order.', to='core.component')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main title of the page.', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='The URL-friendly version of the title. Leave blank to auto-generate.', max_length=200, unique=True)),
                ('content', models.TextField(blank=True, help_text='Main content of the page, can include HTML. This is shown if no template is selected.')),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for SEO, used in meta tags.', max_length=255)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to make this page a draft and hide it from the public.')),
                ('is_homepage', models.BooleanField(default=False, help_text='Set this as the main home page. Only one page can be the homepage.')),
                ('navbar_type', models.CharField(choices=[('HOME', 'Home Page Navbar'), ('BLOG', 'Blog/Detail Page Navbar'), ('GENERIC', 'Generic Back-to-Home Navbar')], default='GENERIC', help_text='Select the type of navigation bar to display on this page.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, help_text='Select a pre-defined template set to render on this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('health_check', 'Health Check Alert'), ('performance', 'Performance Alert'), ('resource', 'Resource Alert'), ('security', 'Security Alert'), ('maintenance', 'Maintenance Alert'), ('custom', 'Custom Alert')], help_text='Type of alert', max_length=50)),
                ('title', models.CharField(help_text='Alert title', max_length=200)),
                ('message', models.TextField(help_text='Detailed alert message')),
                ('severity', models.CharField(choices=[('info', '🔵 Info'), ('warning', '🟡 Warning'), ('critical', '🔴 Critical'), ('emergency', '🚨 Emergency')], help_text='Alert severity level', max_length=20)),
                ('source_metric', models.CharField(blank=True, help_text='Source health metric that triggered this alert', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional alert metadata')),
                ('resolved', models.BooleanField(default=False, help_text='Whether this alert has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this alert was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how this alert was resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this alert was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this alert was last updated')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Alert',
                'verbose_name_plural': 'System Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', '-created_at'], name='core_system_alert_t_a841ae_idx'), models.Index(fields=['severity', '-created_at'], name='core_system_severit_d6e813_idx'), models.Index(fields=['resolved', '-created_at'], name='core_system_resolve_4db000_idx'), models.Index(fields=['-created_at'], name='core_system_created_2a990a_idx')],
            },
        ),
    ]
