# Generated by Django 5.2.3 on 2025-07-11 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A friendly name for this component (e.g., 'Homepage Hero Section').", max_length=100, unique=True)),
                ('filename', models.SlugField(help_text="The component identifier (e.g., 'hero-section').", max_length=100, unique=True)),
                ('content', models.TextField(blank=True, help_text='The HTML content of the component.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for this template set (e.g., 'Homepage Layout').", max_length=100, unique=True)),
                ('files', models.ManyToManyField(blank=True, help_text='Select the files that make up this template set. They will be included in order.', to='core.component')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main title of the page.', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='The URL-friendly version of the title. Leave blank to auto-generate.', max_length=200, unique=True)),
                ('content', models.TextField(blank=True, help_text='Main content of the page, can include HTML. This is shown if no template is selected.')),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for SEO, used in meta tags.', max_length=255)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to make this page a draft and hide it from the public.')),
                ('is_homepage', models.BooleanField(default=False, help_text='Set this as the main home page. Only one page can be the homepage.')),
                ('navbar_type', models.CharField(choices=[('HOME', 'Home Page Navbar'), ('BLOG', 'Blog/Detail Page Navbar'), ('GENERIC', 'Generic Back-to-Home Navbar')], default='GENERIC', help_text='Select the type of navigation bar to display on this page.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, help_text='Select a pre-defined template set to render on this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
