# Generated by Django 5.2.3 on 2025-06-25 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Select a pre-defined template set to render on this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template'),
        ),
    ]
