# Generated by Django 5.2.3 on 2025-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_component_created_at_component_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='slug',
            field=models.SlugField(blank=True, help_text='The URL-friendly version of the title. Leave blank to auto-generate.', max_length=200, unique=True),
        ),
    ]
