# Generated by Django 5.2.3 on 2025-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Script', max_length=200)),
                ('script_code', models.TextField(help_text='Write your Python script here')),
                ('output', models.TextField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Script Runner',
                'verbose_name_plural': 'Script Runners',
            },
        ),
    ]
