# Generated by Django 5.2.3 on 2025-06-25 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_newslettersubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='The user who authored the post.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select one or more categories for this post.', related_name='posts', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='The main content of the post. Can contain HTML.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A short summary for list views and meta descriptions.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='An optional header image for the post.', null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Mark as featured to display prominently on the blog's main page."),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title. Leave blank to auto-generate.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Automatically tracked view count.'),
        ),
    ]
