# Generated by Django 5.2.3 on 2025-07-25 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add_engagement_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Author biography (max 500 characters)', max_length=500)),
                ('website', models.URLField(blank=True, help_text="Author's personal or professional website")),
                ('twitter', models.CharField(blank=True, help_text='Twitter username (without @)', max_length=50)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github', models.CharField(blank=True, help_text='GitHub username', max_length=50)),
                ('instagram', models.CharField(blank=True, help_text='Instagram username (without @)', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, help_text='Author profile picture', null=True, upload_to='author_pics/')),
                ('is_guest_author', models.BooleanField(default=False, help_text='Mark as guest author with limited permissions')),
                ('guest_author_email', models.EmailField(blank=True, help_text='Contact email for guest authors (if different from user email)', max_length=254)),
                ('guest_author_company', models.CharField(blank=True, help_text='Company or organization for guest authors', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this author profile is active and should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user account associated with this author profile', on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name', 'user__username'],
                'indexes': [models.Index(fields=['is_guest_author'], name='blog_author_is_gues_d8b558_idx'), models.Index(fields=['is_active'], name='blog_author_is_acti_4c5854_idx'), models.Index(fields=['user'], name='blog_author_user_id_5f9e60_idx')],
            },
        ),
    ]
