# Generated by Django 5.2.3 on 2025-07-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_add_multimedia_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mediaitem',
            new_name='blog_mediai_post_id_61caea_idx',
            old_name='blog_mediai_post_id_b8e7a5_idx',
        ),
        migrations.RenameIndex(
            model_name='mediaitem',
            new_name='blog_mediai_is_feat_b0da66_idx',
            old_name='blog_mediai_is_feat_b69323_idx',
        ),
        migrations.RenameIndex(
            model_name='mediaitem',
            new_name='blog_mediai_order_87b053_idx',
            old_name='blog_mediai_order_a1b2c3_idx',
        ),
    ]
