# Generated by Django 5.2.3 on 2025-08-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_blog_mediai_post_id_b8e7a5_idx_blog_mediai_post_id_61caea_idx_and_more'),
        ('blog', '0009_add_linkedin_models'),
    ]

    operations = [
    ]
