# Generated by Django 5.2.3 on 2025-08-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_merge_20250811_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinpost',
            name='image_error_message',
            field=models.TextField(blank=True, help_text='Error message if image upload failed'),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='image_upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of image upload process', max_length=20),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='Original image URLs that were processed'),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='media_ids',
            field=models.JSONField(blank=True, default=list, help_text='LinkedIn media IDs for uploaded images'),
        ),
    ]
