# Generated by Django 5.2.3 on 2025-08-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_add_linkedin_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinconfig',
            name='custom_hashtag_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Custom hashtag rules per category (JSON format)'),
        ),
        migrations.AddField(
            model_name='linkedinconfig',
            name='enable_hashtags',
            field=models.BooleanField(default=True, help_text='Enable automatic hashtag generation for LinkedIn posts'),
        ),
        migrations.AddField(
            model_name='linkedinconfig',
            name='enable_image_posting',
            field=models.BooleanField(default=True, help_text='Include images in LinkedIn posts when available'),
        ),
        migrations.AddField(
            model_name='linkedinconfig',
            name='hashtag_blacklist',
            field=models.JSONField(blank=True, default=list, help_text='Words to exclude from hashtag generation (JSON array)'),
        ),
        migrations.AddField(
            model_name='linkedinconfig',
            name='image_posting_strategy',
            field=models.CharField(choices=[('always', 'Always include images when available'), ('never', 'Never include images (text-only posts)'), ('category_based', 'Based on post category settings')], default='always', help_text='Strategy for including images in LinkedIn posts', max_length=20),
        ),
        migrations.AddField(
            model_name='linkedinconfig',
            name='max_hashtags',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of hashtags per LinkedIn post'),
        ),
    ]
