# Generated by Django 5.2.3 on 2025-08-25 07:28

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def update_linkedin_config_defaults(apps, schema_editor):
    """
    Data migration to ensure all existing LinkedInConfig instances have proper default values
    for the new hashtag and image posting configuration fields.
    """
    LinkedInConfig = apps.get_model('blog', 'LinkedInConfig')
    
    updated_count = 0
    
    for config in LinkedInConfig.objects.all():
        needs_update = False
        
        # Check and set hashtag configuration defaults
        if config.enable_hashtags is None:
            config.enable_hashtags = True
            needs_update = True
        
        if config.max_hashtags is None:
            config.max_hashtags = 5
            needs_update = True
        
        if config.custom_hashtag_rules is None:
            config.custom_hashtag_rules = {}
            needs_update = True
        
        if config.hashtag_blacklist is None:
            config.hashtag_blacklist = []
            needs_update = True
        
        # Check and set image posting configuration defaults
        if config.enable_image_posting is None:
            config.enable_image_posting = True
            needs_update = True
        
        if not config.image_posting_strategy:
            config.image_posting_strategy = 'always'
            needs_update = True
        
        if config.category_image_overrides is None:
            config.category_image_overrides = {}
            needs_update = True
        
        if needs_update:
            config.save()
            updated_count += 1
            logger.info(f"Updated LinkedInConfig {config.id} with default values")
    
    if updated_count > 0:
        logger.info(f"Updated {updated_count} LinkedInConfig instances with default values")
    else:
        logger.info("All LinkedInConfig instances already have proper default values")


def reverse_update_linkedin_config_defaults(apps, schema_editor):
    """
    Reverse migration - this is a no-op since we're only setting defaults
    and don't want to remove user data.
    """
    logger.info("Reverse migration for LinkedIn config defaults - no action needed")


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_add_category_image_overrides'),
    ]

    operations = [
        migrations.RunPython(
            update_linkedin_config_defaults,
            reverse_update_linkedin_config_defaults,
        ),
    ]
